mysql:
  dialect: "mysql"
  database: "pop_test"
  host: '{{ envOr "MYSQL_HOST" "127.0.0.1" }}'
  port: '{{ envOr "MYSQL_PORT" "3306" }}'
  user: '{{ envOr "MYSQL_USER"  "root" }}'
  password: '{{ envOr "MYSQL_PASSWORD"  "root#" }}'
  options:
    readTimeout: 5s

postgres:
  url: '{{ envOr "POSTGRESQL_URL" "postgres://postgres:postgres%23@localhost:5433/pop_test?sslmode=disable" }}'
  pool: 25

cockroach:
  url: postgres://{{ envOr "COCKROACH_USER" "root" }}:{{ envOr "COCKROACH_PASSWORD" "" }}@{{ envOr "COCKROACH_HOST" "127.0.0.1" }}:{{ envOr "COCKROACH_PORT" "26257" }}/pop_test?application_name=cockroach&sslmode=disable
  dialect: "cockroach"

cockroach_ssl:
  dialect: "cockroach"
  url: "postgres://root@localhost:26259/pop_test?sslmode=require&sslrootcert=./crdb/certs/ca.crt&sslkey=./crdb/certs/client.root.key&sslcert=./crdb/certs/client.root.crt"

sqlite:
  dialect: "sqlite3"
  database: "tmp/test.sqlite"
  options:
    lock: true

ydb:
  dialect: "ydb"
  url: '{{ envOr "YDB_URL" "grpc://localhost:2136/local?query_mode=query&go_query_bind=numeric,declare,table_path_prefix(/local)" }}'

